BTNhom_MocPhuc/Controllers/QuanTriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using BTNhom_MocPhuc.Models;
using System.Data.Entity;

namespace BTNhom_MocPhuc.Controllers
{
    public class QuanTriController : Controller
    {
        private MocPhucEntities db = new MocPhucEntities();
       

        string LayMaNV()
        {
            var maMax = db.NHANVIENs.ToList().Select(n => n.MANV).Max();
            int maNV;
            if (maMax == null)
            {
                maNV = 1;
            }
            else
            {
                maNV = int.Parse(maMax.Substring(2)) + 1;
            }

            string NV = String.Concat("00", maNV.ToString());
            return "NV" + NV.Substring(maNV.ToString().Length - 1);
        }

        //Dùng chuyển đổi một chuỗi về dạng mã hóa MD5
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }

        // GET: QuanTri
        public ActionResult Index()
        {
            if(Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                NHANVIEN nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
                ViewBag.Admin = nv.IsAdmin;
                return View();
            }
            else
            {
                return RedirectToAction("DangNhap");
            }
            
        }


        [HttpGet]
        public ActionResult DoanhThu(string tuNgay = "", string denNgay = "")
        {
            NHANVIEN nv = null;
            if(Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            if (nv.IsAdmin == true)
            {
                ViewBag.TuNgay = tuNgay;
                ViewBag.DenNgay = denNgay;

                var hd = db.HOADONs.SqlQuery("SELECT * FROM HOADON WHERE NGAYDATHANG > '" + tuNgay + "' AND NGAYDATHANG < '" + denNgay + "'");
                if (hd.Count() == 0)
                    ViewBag.TB = "Không có thông tin thống kê.";
                return View(hd.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

        }


        public ActionResult DangKy()
        {
            NHANVIEN nv = null;
            if (Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            if (nv.IsAdmin == true)
            {
                return View();
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy([Bind(Include = "MANV,TEN,TENDEM,HO,NGAYSINH,DIACHI,SDT,AVATAR,EMAIL,TENDN,PASS,IsAdmin,ConfirmPassword")] NHANVIEN nv)
        {

            if (ModelState.IsValid)
            {
                var check = db.NHANVIENs.FirstOrDefault(s => s.EMAIL == nv.EMAIL);
                var check2 = db.NHANVIENs.FirstOrDefault(s => s.TENDN == nv.TENDN);
                if (check == null && check2 == null)
                {
                    nv.MANV = LayMaNV();
                    nv.PASS = GetMD5(nv.PASS);
                    nv.AVATAR = "employee.png";
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.NHANVIENs.Add(nv);
                    db.SaveChanges();
                    return Redirect("/NHANVIEN/Index");

                }
                else if(check != null)
                {
                    ViewBag.error = "Email đã tồn tại !!!";
                    
                    return View();
                }

                else if(check2 != null)
                {
                    ViewBag.error2 = "Tên đăng nhập đã tồn tại";
                    return View();
                }
            }

            return View();
        }

        public ActionResult DangNhap()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangNhap(string TENDN, string PASS)
        {
            if (ModelState.IsValid)
            {
                var f_password = GetMD5(PASS);
                var data = db.NHANVIENs.Where(s => s.TENDN.Equals(TENDN) && s.PASS.Equals(f_password)).ToList();
                if (data.Count() > 0)
                {
                    //tạo session
                    Session["TENNV"] = data.FirstOrDefault().TEN;
                    Session["AVATARNV"] = data.FirstOrDefault().AVATAR;
                    Session["MANV"] = data.FirstOrDefault().MANV;

                    HttpCookie ck = new HttpCookie("nvCookies");
                    ck["idNV"] = data.FirstOrDefault().MANV;
                    //tạo Cookies
                    Response.Cookies.Add(ck);
                    ck.Expires = DateTime.Now.AddDays(1); //giới hạn thời gian 1 ngày

                    return Redirect("/QuanTri/Index");
                }
                else
                {
                    ViewBag.error = "Tên đang nhập hoặc mật khẩu không đúng !!!";
                    return View();
                }
            }
            return View();
        }

        //Logout
        public ActionResult DangXuat()
        {
            //Xóa session
            Session.Clear();
            //Xóa cookies
            if (Request.Cookies["nvCookies"] != null)
            {
                HttpCookie myCookie = new HttpCookie("nvCookies");
                myCookie.Expires = DateTime.Now.AddDays(-1d);
                Response.Cookies.Add(myCookie);
            }

            return RedirectToAction("DangNhap");
        }

        [HttpGet]
        public ActionResult XacNhanHD()
        {
            NHANVIEN nv = null;
            if (Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }


            if (nv.IsAdmin == true)
            {
                var orders = db.HOADONs.Where(x => x.TINHTRANG == "TT1").ToList();
                ViewBag.Count = orders.Count;

                return View(orders);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            
        }

        [HttpGet]
        public ActionResult NhanGiaoHang()
        {
            NHANVIEN nv = null;
            if (Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }


            if (nv.IsAdmin == false)
            {
                var orders = db.HOADONs.Where(x => x.TINHTRANG == "TT2").ToList();
                ViewBag.Count = orders.Count;

                return View(orders);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            
        }

        [HttpGet]
        public ActionResult DaGiaoHang()
        {
            NHANVIEN nv = null;
            if (Session["MANV"] != null)
            {
                string maNV = Session["MANV"].ToString();
                nv = db.NHANVIENs.FirstOrDefault(x => x.MANV == maNV);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }


            if (nv.IsAdmin == false)
            {
                string maNVGiao = Session["MANV"].ToString();
                var orders = db.HOADONs.Where(x => x.MANVGIAO == maNVGiao).ToList();
                ViewBag.Count = orders.Count;

                return View(orders);
            }
            else
            {
                return RedirectToAction("DangNhap");
            }

            
        }

        public JsonResult XacNhan(string id)
        {
            HOADON hd = db.HOADONs.FirstOrDefault(x => x.IDHD.ToString() == id);
            hd.TINHTRANG = "TT2";
            hd.MANVDUYET = Session["MANV"].ToString();
            db.Entry(hd).State = EntityState.Modified;
            db.SaveChanges();

            return Json(new { status = true });
        }

        public JsonResult GiaoDon(string id)
        {
            HOADON hd = db.HOADONs.FirstOrDefault(x => x.IDHD.ToString() == id);
            hd.TINHTRANG = "TT3";
            hd.MANVGIAO = Session["MANV"].ToString();
            db.Entry(hd).State = EntityState.Modified;
            db.SaveChanges();

            return Json(new { status = true });
        }

        public JsonResult DaGiao(string id)
        {
            HOADON hd = db.HOADONs.FirstOrDefault(x => x.IDHD.ToString() == id);
            hd.TINHTRANG = "TT4";
            hd.NGAYGIAOHANG = DateTime.Today;
            db.Entry(hd).State = EntityState.Modified;
            db.SaveChanges();

            return Json(new { status = true });
        }
    }
}

BTNhom_MocPhuc/Views/QuanTri/DaGiaoHang.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>
@using BTNhom_MocPhuc.Models;

@{
    ViewBag.Title = "DaGiaoHang";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    MocPhucEntities db = new MocPhucEntities();
    int sumMoney = 0;
}

<div class="container">
    <h3 class="mt-3">Xác nhận đã giao hàng</h3>
    <hr />
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr>
                <th scope="col" class="text-center">Mã hóa đơn</th>
                <th scope="col" class="text-center">Ngày đặt</th>
                <th scope="col" class="text-center">Ngày giao</th>
                <th scope="col" class="text-center">Tổng tiền</th>
                <th scope="col" class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Count > 0)
            {
                foreach (var item in Model)
                {
                    var cthd = db.CTHDs.Where(x => x.IDHD == item.IDHD).ToList();
                    foreach (var sp in cthd)
                    {
                        sumMoney += sp.SOLUONG * sp.DONGIA;
                    }

                    <tr>
                        <td class="text-center">#@item.IDHD</td>
                        <td class="text-center">@item.NGAYDATHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@item.NGAYGIAOHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@sumMoney.ToString("N0") vnđ</td>
                        <td class="text-center"><a href="/HOADONs/Details/@item.IDHD" class="text-decoration-none">Xem chi tiết</a></td>
                        <td class="text-center"><a href="#" data-id="@item.IDHD" role="button" class="btn btn-dark btn-daGiao">Đã giao</a></td>
                    </tr>

                    sumMoney = 0;
                }
            }
            else
            {
                <tr>
                    <td colspan="6" class="text-center">Không có đơn hàng cần xác nhận <a href="/HOADONs/Index">Vào danh sách hóa đơn</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    $(".btn-daGiao").off("click").on("click", function (e) {

        e.preventDefault();
        $.ajax({
            url: "/QuanTri/DaGiao",
            data: { id: $(this).data("id") },
            dataType: "json",
            type: "POST",
            success: function (res) {
                if (res.status == true) {
                    window.location.href = "/HOADONs/Index"
                }
            }
        })
    });
</script>

BTNhom_MocPhuc/Views/QuanTri/DangKy.cshtml
@model BTNhom_MocPhuc.Models.NHANVIEN

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
}

<div class="container d-flex flex-column align-items-center">
    <form class="d-flex flex-column w-50 mt-4" method="post" action="/QuanTri/DangKy">
        @Html.AntiForgeryToken()


        <h3 class="text-center">Đăng ký thông tin tài khoản</h3>

        <div class="form-group row my-4">

            <div class="col-4">
                <label for="HO" class="form-label">Họ <span class="text-danger">*</span></label>
                @Html.EditorFor(model => model.HO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HO, "", new { @class = "text-danger" })
            </div>


            <div class="col-4">
                <label for="TENDEM" class="form-label">Tên đệm</label>
                @Html.EditorFor(model => model.TENDEM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENDEM, "", new { @class = "text-danger" })
            </div>



            <div class="col-4">
                <label for="TEN" class="form-label">Tên <span class="text-danger">*</span></label>
                @Html.EditorFor(model => model.TEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            <label for="NGAYSINH" class="form-label">Ngày sinh <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
        </div>

        <div class="form-group mb-3">
            <label for="EMAIL" class="form-label">Email <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", @type = "email", @placeholder = "vd: name@example.com" } })
            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            @if (ViewBag.error != null)
            {
                <span class="badge badge-danger">@ViewBag.error</span>
            }
        </div>

        <div class="form-group mb-3">
            <label for="TENDN" class="form-label">Tên đăng nhập <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.TENDN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENDN, "", new { @class = "text-danger" })
            @if (ViewBag.error2 != null)
            {
                <span class="badge badge-danger">@ViewBag.error2</span>
            }
        </div>

        <div class="form-group mb-3">
            <label for="PASS" class="form-label">Mật khẩu <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
        </div>
        <div class="form-group mb-3">
            <label for="ConfirmPassword" class="form-label">Xác nhận mật khẩu <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })

        </div>

        <div class="form-group mb-3">
            <label for="IsAdmin" class="form-label">Là Admim <span class="text-danger">*</span></label>
            <div class="col-md-10">
                <div class="checkbox">
                    Đúng @Html.RadioButtonFor(model => model.IsAdmin, "True", new { @checked = "checked" }) &nbsp;
                    Không @Html.RadioButtonFor(model => model.IsAdmin, "False")
                    @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group mb-3">
            <label for="SDT" class="form-label">SĐT <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", @placeholder = "vd: 0708488401" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
        <div class="form-group mb-3">
            <label for="DIACHI" class="form-label">Địa chỉ <span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control", @placeholder = "vd: 56KA Cù Lao Thượng, Vĩnh Thọ, Nha Trang, Khánh Hòa" } })
            @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
        </div>




        <button class="btn btn-dark mx-auto mt-3" type="submit">ĐĂNG KÝ</button>
    </form>

    
</div>

BTNhom_MocPhuc/Views/QuanTri/DangNhap.cshtml
@model BTNhom_MocPhuc.Models.NHANVIEN

@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
}


<div class="container d-flex flex-column align-items-center">
    <form class="d-flex flex-column w-50 mt-4" method="post" action="/QuanTri/DangNhap">
        @Html.AntiForgeryToken()


        <h3 class="text-center">Đăng nhập tài khoản</h3>

        @if (ViewBag.error != null)
        {
            <p class="text-center text-danger fw-bold">@ViewBag.error</p>
        }

        <div class="mb-3">
            <label for="TENDN" class="form-label">Tên đăng nhập</label>
            @Html.EditorFor(model => model.TENDN, new { htmlAttributes = new { @class = "form-control"} })
            @Html.ValidationMessageFor(model => model.TENDN, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">
            <label for="PASS" class="form-label">Mật khẩu</label>
            @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
        </div>


        <button class="btn btn-dark mx-auto mt-3" type="submit">ĐĂNG NHẬP</button>
    </form>

    
</div>

BTNhom_MocPhuc/Views/QuanTri/DoanhThu.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>
@using BTNhom_MocPhuc.Models;

@{
    ViewBag.Title = "DoanhThu";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    MocPhucEntities db = new MocPhucEntities();
    int sumMoney = 0;
    int sumDoanhThu = 0;
}

<div class="container">
    <div class="mt-3">
        <a href="/QuanTri/Index" class="text-primary">Quay lại</a>
        <h3>Thống kê doanh thu</h3>
        <hr />
        @using (Html.BeginForm("DoanhThu", "QuanTri", FormMethod.Get))
        {
            @Html.AntiForgeryToken()

            <div class="d-flex flex-column">
                <div class="w-75 mx-auto d-flex flex-row justify-content-evenly">
                    <div class="form-group mt-2">
                        <label for="tuNgay" class="form-label">Từ ngày</label>
                        <input type="date" class="form-control" name="tuNgay" value="@ViewBag.TuNgay" />
                    </div>
                    <div class="form-group mt-2">
                        <label for="denNgay" class="form-label">Đến ngày</label>
                        <input type="date" class="form-control" name="denNgay" value="@ViewBag.DenNgay" />
                    </div>



                </div>
                <div class="mx-auto mt-3">
                    <button type="submit" class="btn btn-dark">Thống kê</button>
                    <a role="button" href="/SANPHAM/TimKiemNC" class="btn btn-dark">Nhập mới</a>
                </div>
            </div>

        }
    </div>

    <div class="mt-4">
        <p class="text-center">@ViewBag.TB</p>
        <table class="table table-striped table-hover mt-4">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Mã hóa đơn</th>
                    <th scope="col" class="text-center">Ngày đặt</th>
                    <th scope="col" class="text-center">Ngày giao</th>
                    <th scope="col" class="text-center">Tổng tiền</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    var cthd = db.CTHDs.Where(x => x.IDHD == item.IDHD).ToList();
                    foreach (var sp in cthd)
                    {
                        sumMoney += sp.SOLUONG * sp.DONGIA;
                    }

                    <tr>
                        <td class="text-center">#@item.IDHD</td>
                        <td class="text-center">@item.NGAYDATHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@item.NGAYGIAOHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@sumMoney.ToString("N0") vnđ</td>
                        <td class="text-center"><a href="/HOADONs/Details/@item.IDHD" class="text-decoration-none">Xem chi tiết</a></td>

                    </tr>

                    sumDoanhThu += sumMoney;
                    sumMoney = 0;
                }
            </tbody>
        </table>

        @if (ViewBag.TB == null)
        {
            <div class="d-flex mt-5">
                <div class="ms-auto mb-3 fs-5"><span class="fw-bold me-3 text-origin">Tổng doanh thu</span><span>@sumDoanhThu.ToString("N0") vnđ</span></div>
            </div>
        }

    </div>
</div>

BTNhom_MocPhuc/Views/QuanTri/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 p-0">
            <img src="/Images/hinhnen.jpeg" alt="hình nền" width="100%">
        </div>
        <div class="col-lg-6">
            <div class="p-4">
                <a class="btn btn-dark mx-2 mb-4" href="/SANPHAM/Index" role="button">Sản phẩm</a>
                <a class="btn btn-dark mx-2 mb-4" href="/KHACHHANG/Index" role="button">Khách hàng</a>
                <a class="btn btn-dark mx-2 mb-4" href="/NHANVIEN/Index" role="button">Nhân viên</a>
                <a class="btn btn-dark mx-2 mb-4" href="/HOADONs/Index" role="button">Hóa đơn</a>
                @if (ViewBag.Admin == false)
                {
                    <a class="btn btn-dark mx-2 mb-4" href="/QuanTri/NhanGiaoHang" role="button">Nhận giao hàng</a>
                    <a class="btn btn-dark mx-2 mb-4" href="/QuanTri/DaGiaoHang" role="button">Xác nhận đã giao hàng</a>
                }

                @if (ViewBag.Admin == true)
                {
                    <a class="btn btn-dark mx-2 mb-4" href="/QuanTri/XacNhanHD" role="button">Xác nhận hóa đơn</a>
                    <a class="btn btn-dark mx-2 mb-4" href="/QuanTri/DangKy" role="button">Đăng kí nhân viên</a>
                    <a class="btn btn-dark mx-2 mb-4" href="/QuanTri/DoanhThu" role="button">Thống kê doanh thu</a>
                }

            </div>
        </div>
    </div>
</div>

BTNhom_MocPhuc/Views/QuanTri/NhanGiaoHang.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>
@using BTNhom_MocPhuc.Models;

@{
    ViewBag.Title = "NhanGiaoHang";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    MocPhucEntities db = new MocPhucEntities();
    int sumMoney = 0;
}

<div class="container">
    <h3 class="mt-3">Đơn hàng chờ giao</h3>
    <hr />
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr>
                <th scope="col" class="text-center">Mã hóa đơn</th>
                <th scope="col" class="text-center">Ngày đặt</th>
                <th scope="col" class="text-center">Ngày giao</th>
                <th scope="col" class="text-center">Tổng tiền</th>
                <th scope="col" class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Count > 0)
            {
                foreach (var item in Model)
                {
                    var cthd = db.CTHDs.Where(x => x.IDHD == item.IDHD).ToList();
                    foreach (var sp in cthd)
                    {
                        sumMoney += sp.SOLUONG * sp.DONGIA;
                    }

                    <tr>
                        <td class="text-center">#@item.IDHD</td>
                        <td class="text-center">@item.NGAYDATHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@item.NGAYGIAOHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@sumMoney.ToString("N0") vnđ</td>
                        <td class="text-center"><a href="/HOADONs/Details/@item.IDHD" class="text-decoration-none">Xem chi tiết</a></td>
                        <td class="text-center"><a href="#" data-id="@item.IDHD" role="button" class="btn btn-dark btn-nhanGH">Giao đơn này</a></td>
                    </tr>

                    sumMoney = 0;
                }
            }
            else
            {
                <tr>
                    <td colspan="6" class="text-center">Không có đơn hàng cần xác nhận <a href="/HOADONs/Index">Vào danh sách hóa đơn</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    $(".btn-nhanGH").off("click").on("click", function (e) {

        e.preventDefault();
        $.ajax({
            url: "/QuanTri/GiaoDon",
            data: { id: $(this).data("id") },
            dataType: "json",
            type: "POST",
            success: function (res) {
                if (res.status == true) {
                    window.location.href = "/HOADONs/Index"
                }
            }
        })
    });
</script>

BTNhom_MocPhuc/Views/QuanTri/XacNhanHD.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>
@using BTNhom_MocPhuc.Models;


@{
    ViewBag.Title = "XacNhanHD";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    MocPhucEntities db = new MocPhucEntities();
    int sumMoney = 0;
}

<div class="container">
    <h3 class="mt-3">Đơn hàng cần xác nhận</h3>
    <hr />
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr>
                <th scope="col" class="text-center">Mã hóa đơn</th>
                <th scope="col" class="text-center">Ngày đặt</th>
                <th scope="col" class="text-center">Ngày giao</th>
                <th scope="col" class="text-center">Tổng tiền</th>
                <th scope="col" class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Count > 0)
            {
                foreach (var item in Model)
                {
                    var cthd = db.CTHDs.Where(x => x.IDHD == item.IDHD).ToList();
                    foreach (var sp in cthd)
                    {
                        sumMoney += sp.SOLUONG * sp.DONGIA;
                    }

                    <tr>
                        <td class="text-center">#@item.IDHD</td>
                        <td class="text-center">@item.NGAYDATHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@item.NGAYGIAOHANG.Value.ToString("dd/MM/yyyy")</td>
                        <td class="text-center">@sumMoney.ToString("N0") vnđ</td>
                        <td class="text-center"><a href="/HOADONs/Details/@item.IDHD" class="text-decoration-none">Xem chi tiết</a></td>
                        <td class="text-center"><a href="#" data-id="@item.IDHD" role="button" class="btn btn-dark btn-xacNhan">Xác nhận</a></td>
                    </tr>

                    sumMoney = 0;
                }
            }
            else
            {
                <tr>
                    <td colspan="6" class="text-center">Không có đơn hàng cần xác nhận <a href="/HOADONs/Index">Vào danh sách hóa đơn</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    $(".btn-xacNhan").off("click").on("click", function (e) {

        e.preventDefault();
        $.ajax({
            url: "/QuanTri/XacNhan",
            data: { id: $(this).data("id") },
            dataType: "json",
            type: "POST",
            success: function (res) {
                if (res.status == true) {
                    window.location.href = "/HOADONs/Index"
                }
            }
        })
    });
</script>