BTNhom_MocPhuc/Models/NHANVIEN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom_MocPhuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.HOADONs1 = new HashSet<HOADON>();
        }

        public string MANV { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [Display(Name = "Tên")]
        public string TEN { get; set; }
        [Display(Name = "Tên đệm")]
        public string TENDEM { get; set; }
        [Display(Name = "Họ")]
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        public string HO { get; set; }
        [Display(Name = "Ngày sinh")]
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        public string DIACHI { get; set; }
        [Display(Name = "SĐT")]
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        public string SDT { get; set; }
       
        public string AVATAR { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [Display(Name = "Tên đăng nhập")]
        public string TENDN { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [Display(Name = "Mật khẩu")]
        public string PASS { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [Display(Name = "Là Admin")]
        public bool IsAdmin { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Không được bỏ trống !!!")]
        [System.ComponentModel.DataAnnotations.Compare("PASS", ErrorMessage = "Mật khẩu không khớp !!!")]
        [Display(Name = "Xác nhận mật khẩu")]
        public string ConfirmPassword { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs1 { get; set; }
    }
}

BTNhom_MocPhuc/Controllers/NHANVIENController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTNhom_MocPhuc.Models;

namespace BTNhom_MocPhuc.Controllers
{
    public class NHANVIENController : Controller
    {
        private MocPhucEntities db = new MocPhucEntities();

        // GET: NHANVIEN
        public ActionResult Index()
        {
            if(Session["MANV"] != null)
            {
                return View(db.NHANVIENs.ToList());
            }
            else
            {
                return Redirect("/QuanTri/DangNhap");
            }
        }

        // GET: NHANVIEN/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }


        // GET: NHANVIEN/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // POST: NHANVIEN/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MANV,TEN,TENDEM,HO,NGAYSINH,DIACHI,SDT,AVATAR,EMAIL,TENDN,PASS,IsAdmin,ConfirmPassword")] NHANVIEN nHANVIEN)
        {
            var imgNV = Request.Files["Avatar"];
            try
            {
                //Lấy thông tin từ input type=file có tên Avatar
                string postedFileName = System.IO.Path.GetFileName(imgNV.FileName);
                //Lưu hình đại diện về Server
                var path = Server.MapPath("/Images/" + postedFileName);
                imgNV.SaveAs(path);
            }
            catch { }

            if (ModelState.IsValid)
            {
                db.Entry(nHANVIEN).State = EntityState.Modified;
                db.SaveChanges();
            }
            return View(nHANVIEN);
        }


       
    }
}

BTNhom_MocPhuc/Views/NHANVIEN/Details.cshtml
@model BTNhom_MocPhuc.Models.NHANVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    string isAdmin = "";
}

<div class="container">
    <h3 class="mt-4">Thông tin nhân viên</h3>
    <hr />
    <table cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
        <tr>
            <td>
                <table cellpadding="2" cellspacing="10">
                    <tr>
                        <td rowspan="8"><img src="/Images/@Html.DisplayFor(model => model.AVATAR)" width="100" height="100" style="border-radius: 50px; margin-right: 8px" /></td>
                        <td class="fw-bold">Mã nhân viên:</td>
                        <td class="ps-2">@Html.DisplayFor(model => model.MANV)</td>
                    </tr>
                    <tr>
                        <td class="fw-bold">Họ tên:</td>
                        <td class="ps-2">@Model.HO @Model.TENDEM @Model.TEN</td>
                    </tr>

                    <tr>
                        <td class="fw-bold">Ngày sinh:</td>
                        <td class="ps-2">@Model.NGAYSINH.Value.ToString("dd/MM/yyyy")</td>
                    </tr>

                    <tr>
                        <td class="fw-bold">Địa chỉ:</td>
                        <td class="ps-2">@Html.DisplayFor(model => model.DIACHI)</td>
                    </tr>

                    <tr>
                        <td class="fw-bold">SĐT:</td>
                        <td class="ps-2">@Html.DisplayFor(model => model.SDT)</td>
                    </tr>

                    <tr>
                        <td class="fw-bold">Email:</td>
                        <td class="ps-2">@Html.DisplayFor(model => model.EMAIL)</td>
                    </tr>

                    <tr>
                        <td class="fw-bold">Là Admin:</td>
                        <td class="ps-2">
                            @{if (Model.IsAdmin == true)
                                { isAdmin = "Đúng"; }
                                else
                                { isAdmin = "Không"; }
                            }
                            @isAdmin
                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>
    <p class="my-5">
        @Html.ActionLink("Quay lại", "Index")
    </p>
</div>

BTNhom_MocPhuc/Views/NHANVIEN/Edit.cshtml
@model BTNhom_MocPhuc.Models.NHANVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var fileupload = $("#Avatar");
            var image = $("#FileUpload");
            image.click(function () {
                fileupload.click();
            });
            fileupload.change(function () {
                var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                document.getElementById("AVATAR").value = fileName;
            });
        });
    </script>
}

<div class="container">
    @using (Html.BeginForm("Edit", "NHANVIEN", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal w-50 ">
        <h3 class="mt-4">Thông tin cá nhân</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MANV)
        @Html.HiddenFor(model => model.TENDN)
        @Html.HiddenFor(model => model.PASS)
        @Html.HiddenFor(model => model.IsAdmin)

        <div class="form-group my-4">
            <div class="">
                @Html.HiddenFor(model => model.AVATAR)
                <img src="/Images/@Model.AVATAR" alt="@Model.TEN" width="150" height="150" style="border-radius: 200px" />
                <input type="file" name="Avatar" id="Avatar" />
            </div>
        </div>

        <div class="form-group row my-4">

            <div class="col-4">
                @Html.LabelFor(model => model.HO, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.HO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HO, "", new { @class = "text-danger" })
            </div>


            <div class="col-4">
                @Html.LabelFor(model => model.TENDEM, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TENDEM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENDEM, "", new { @class = "text-danger" })
            </div>



            <div class="col-4">
                @Html.LabelFor(model => model.TEN, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.TEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control", @disable="disable"} })
            @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
        </div>

        <div class="form-group my-4">
            @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group my-4">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger", @disable = "disable" })
        </div>


        <div class="form-group mb-3">
            <input type="password" name="ConfirmPassword" value="@Model.PASS" hidden="hidden" />
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-dark">Lưu thay đổi</button>
            </div>
        </div>
    </div>
    }
</div>

BTNhom_MocPhuc/Views/NHANVIEN/Index.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.NHANVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TENNV", rowsPerPage: 10);
}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: blue;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: #FFAD33;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: left;
    }

    a {
        text-decoration: none;
        color: #000;
    }
</style>

<div class="container">
    <h3 class="my-3">Danh sách nhân viên</h3>

    @grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]  // colums in grid
        {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MANV","Mã nhân viên"), //the model fields to display
            grid.Column("","Họ tên", format: @<text> @item.HO @item.TENDEM @item.TEN </text>),
            grid.Column("NGAYSINH","Ngày sinh", format:@<text> @item.NGAYSINH.ToString("dd/MM/yyyy")</text>),
            grid.Column("DIACHI","Địa chỉ"),
            grid.Column("SDT","SĐT"),
            grid.Column("IsAdmin","Là Admim",format: (@item) => @item.IsAdmin==true?"Đúng":"Không"),
            grid.Column(format: @<text>
                <a href="@Url.Action("Details", new { id = item.MANV})" class="edit-btn text-primary">
                    Chi tiết
                </a>
            </text>),

            }
    )
</div>