BTNhom_MocPhuc/Models/HOADON.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom_MocPhuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int IDHD { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDATHANG { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
        public string NOIGIAOHANG { get; set; }
        public string MANVDUYET { get; set; }
        public string MANVGIAO { get; set; }
        public string MAPT { get; set; }
        public string TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
        public virtual PHUONGTHUCTT PHUONGTHUCTT { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}

BTNhom_MocPhuc/Controllers/HOADONsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTNhom_MocPhuc.Models;

namespace BTNhom_MocPhuc.Controllers
{
    public class HOADONsController : Controller
    {
        private MocPhucEntities db = new MocPhucEntities();

        // GET: HOADONs
        public ActionResult Index()
        {
            if(Session["MANV"] != null)
            {
                var hOADONs = db.HOADONs.Include(h => h.KHACHHANG).Include(h => h.NHANVIEN).Include(h => h.NHANVIEN1).Include(h => h.PHUONGTHUCTT).Include(h => h.TINHTRANG1);
                return View(hOADONs.ToList());
            }
            else
            {
                return Redirect("/QuanTri/DangNhap");
            }
        }

        [HttpGet]
        public ActionResult TimKiemNC(string MAHD = "", string MANVDUYET = "", string MANVGIAO = "", string MAPT = "" , string MATT = "")
        {
            if(Session["MANV"] != null)
            {
                ViewBag.MAHD = MAHD;
                ViewBag.MANVDUYET = MANVDUYET;
                ViewBag.MANVGIAO = MANVGIAO;
                ViewBag.MAPT = new SelectList(db.PHUONGTHUCTTs, "MAPT", "TENPT");
                ViewBag.MATT = new SelectList(db.TINHTRANGs, "MATINHTRANG", "TENTINHTRANG");
                var hd = db.HOADONs.SqlQuery("HoaDon_TimKiem'" + MAHD + "','" + MANVDUYET + "','" + MANVGIAO + "','" + MAPT + "','" + MATT + "'");
                if (hd.Count() == 0)
                    ViewBag.TB = "Không có thông tin tìm kiếm.";
                return View(hd.ToList());
            }
            else
            {
                return Redirect("/QuanTri/DangNhap");
            }
        }

        // GET: HOADONs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var detailOrders = db.CTHDs.Where(x => x.IDHD == id).Include(x => x.SANPHAM).ToList();


            ViewBag.IDHD = id;

            var hd = db.HOADONs.FirstOrDefault(x => x.IDHD == id);


            ViewBag.TT = db.TINHTRANGs.FirstOrDefault(x => x.MATINHTRANG == hd.TINHTRANG).TENTINHTRANG;

            ViewBag.NgayDat = hd.NGAYDATHANG;
            ViewBag.KH = db.KHACHHANGs.FirstOrDefault(x => x.MAKH == hd.MAKH);

            ViewBag.ptThanhToan = db.PHUONGTHUCTTs.FirstOrDefault(x => x.MAPT == hd.MAPT).TENPT;

            
            if (detailOrders == null)
            {
                return HttpNotFound();
            }

            return View(detailOrders);
        }

      
    }
}

BTNhom_MocPhuc/Views/HOADONs/Details.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.CTHD>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    int sumMoney = 0;
}

<div class="container">
    <h3 class="mt-3">Chi tiết hóa đơn #@ViewBag.IDHD <span class="fw-light">- @ViewBag.TT</span></h3>
    <hr />

    <div class="my-4 row">
        <div class="col-6">
            <p><span class="fw-bold">Tên người nhận:</span> @ViewBag.KH.HO @ViewBag.KH.TENDEM @ViewBag.KH.TEN</p>
            <p><span class="fw-bold">SĐT:</span> @ViewBag.KH.SDT</p>
            <p><span class="fw-bold">Nơi nhận:</span> @ViewBag.KH.DIACHI</p>
        </div>
        <div class="col-6">
            <p><span class="fw-bold">Ngày đặt hàng:</span> @ViewBag.NgayDat.ToString("dd/MM/yyyy")</p>
            <p><span class="fw-bold">Phương thức thanh toán:</span> @ViewBag.ptThanhToan</p>
        </div>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr>
                <th scope="col" class="text-center">Hình ảnh</th>
                <th scope="col" class="text-center">Tên sản phẩm</th>
                <th scope="col" class="text-center">Đơn giá</th>
                <th scope="col" class="text-center">Số lượng</th>
                <th scope="col" class="text-center">Thành tiền</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        <img src="/Images/@item.SANPHAM.IMG" width="64px" />
                    </td>
                    <td class="text-center">@item.SANPHAM.TENSP</td>
                    <td class="text-center">@item.SANPHAM.GIABAN.Value.ToString("N0") vnđ</td>
                    <td class="text-center w-25">
                        <div class="form-group">

                            <input class="d-inline form-control w-20 text-center soluong" type="text" disabled="disabled" value="@item.SOLUONG">

                        </div>
                    </td>
                    <td class="text-center">@((item.SANPHAM.GIABAN * item.SOLUONG).Value.ToString("N0")) vnđ</td>
                    
                </tr>
                sumMoney += ((int)item.SANPHAM.GIABAN * item.SOLUONG);
                ViewBag.sumMoney = sumMoney;
            }
        </tbody>
    </table>

    <div class="mt-5">
        
        <div class="d-flex flex-column">
            <div class="ms-auto mb-3 fs-5"><span class="fw-bold me-3 text-origin">Tổng tiền </span><span>@ViewBag.sumMoney.ToString("N0") vnđ</span></div>
        </div>
    </div>
</div>

BTNhom_MocPhuc/Views/HOADONs/Index.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "NGAYDATHANG", rowsPerPage: 10);
    
}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: blue;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: #FFAD33;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: left;
    }

    a {
        text-decoration: none;
        color: #000;
    }
</style>

<div class="container">
    <h3 class="my-3">Danh sách đơn hàng</h3>
    <p><a href="/HOADONs/TimKiemNC">Tìm kiếm</a></p>
    @grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]  // colums in grid
        {
            grid.Column("IDHD","Mã hóa đơn", format: @<text>#@item.IDHD</text>), //the model fields to display
            grid.Column("NGAYDATHANG","Ngày đặt", format:@<text> @item.NGAYDATHANG.ToString("dd/MM/yyyy")</text>),
            grid.Column("NGAYGIAOHANG","Ngày giao hàng", format:@<text> @item.NGAYGIAOHANG.ToString("dd/MM/yyyy")</text>),
            grid.Column("","Nhân viên duyệt", format: (@item) => item.MANVDUYET == null?"": item.NHANVIEN.HO+" "+item.NHANVIEN.TENDEM+" "+item.NHANVIEN.TEN),
            grid.Column("","Nhân viên giao", format: (@item) => item.MANVGIAO == null?"": item.NHANVIEN1.HO+" "+item.NHANVIEN1.TENDEM+" "+item.NHANVIEN1.TEN),
            grid.Column("TINHTRANG1.TENTINHTRANG","Tình trạng"),
            grid.Column(format: @<text>
                <a href="@Url.Action("Details", new { id = item.IDHD})" class="edit-btn text-primary">
                    Chi tiết
                </a>
            </text>),

         }
    )
</div>

BTNhom_MocPhuc/Views/HOADONs/TimKiemNC.cshtml
@model IEnumerable<BTNhom_MocPhuc.Models.HOADON>

@{
    ViewBag.Title = "TimKiemNC";
    Layout = "~/Views/Shared/LayoutQuanTri.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TENSP", rowsPerPage: 10);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: blue;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: #FFAD33;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: left;
    }

    a {
        text-decoration: none;
        color: #000;
    }
</style>

<div class="container">
    <div class="mt-5">
        <a href="/HOADONs/Index" class="text-primary">Quay lại</a>
        <h3>Tìm kiếm hóa đơn</h3>
        @using (Html.BeginForm("TimKiemNC", "HOADONs", FormMethod.Get))
        {
            @Html.AntiForgeryToken()

    <div class="d-flex flex-column">

        <div class="w-75 mx-auto d-flex flex-row justify-content-evenly">
            <div class="form-group mb-1 mt-2 my-2">
                <label for="MAHD" class="form-label">Mã hóa đơn</label>
                <input type="text" class="form-control" name="MAHD" value="@ViewBag.MAHD" />
            </div>
            <div class="form-group mb-1 mt-2">
                <label for="MANVDUYET" class="form-label">Mã nhân viên duyệt</label>
                <input type="text" class="form-control" name="MANVDUYET" value="@ViewBag.MANVDUYET" />
            </div>
            <div class="form-group mb-1 mt-2">
                <label for="MANVGIAO" class="form-label">Mã nhân viên giao</label>
                <input type="text" class="form-control" name="MANVGIAO" value="@ViewBag.MANVGIAO" />
            </div>
        </div>

       

        <div class="w-75 mx-auto d-flex flex-row justify-content-evenly">

            <div class="form-group mb-1 mt-2 my-2">
                <label for="MAPT" class="form-label">Phương thức thanh toán</label>
                @Html.DropDownList("MAPT", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
            </div>

            <div class="form-group mb-1 mt-2 my-2">
                <label for="MATT" class="form-label">Tình trạng</label>
                @Html.DropDownList("MATT", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="mx-auto mt-3">
            <button type="submit" class="btn btn-dark">Tìm kiếm</button>
            <a role="button" href="/HOADONs/TimKiemNC" class="btn btn-dark">Nhập mới</a>
        </div>
    </div>

        }
    </div>

    <div class="gridContent">
        <p class="text-center">@ViewBag.TB</p>
        @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
        columns: new[]  // colums in grid
            {
            grid.Column("IDHD","Mã hóa đơn", format: @<text>#@item.IDHD</text>), //the model fields to display
            grid.Column("NGAYDATHANG","Ngày đặt", format:@<text> @item.NGAYDATHANG.ToString("dd/MM/yyyy")</text>),
            grid.Column("NGAYGIAOHANG","Ngày giao hàng", format:@<text> @item.NGAYGIAOHANG.ToString("dd/MM/yyyy")</text>),
            grid.Column("MANVDUYET","Nhân viên duyệt", format: (@item) => item.MANVDUYET == null?"": item.NHANVIEN.HO+" "+item.NHANVIEN.TENDEM+" "+item.NHANVIEN.TEN),
            grid.Column("MANVGIAO","Nhân viên giao", format: (@item) => item.MANVGIAO == null?"": item.NHANVIEN1.HO+" "+item.NHANVIEN1.TENDEM+" "+item.NHANVIEN1.TEN),
            grid.Column("TINHTRANG1.TENTINHTRANG","Tình trạng"),
            grid.Column(format: @<text>
                <a href="@Url.Action("Details", new { id = item.IDHD})" class="edit-btn text-primary">
                    Chi tiết
                </a>
            </text>),

        }
    )
    </div>
</div>